name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: IGNIT3-xD
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate Contribution Snake'
          add: 'dist'
          default_author: github_actions
